  name: Hello World
  author: Murtaja Kadiyani
  description: Print Greetings with Time
  inputs:
    who-to-greet:
      description: "Who to greet"
      required: true
      default: MAK
  outputs:
    time:
      description: "The greeting time"
  runs:
    using: "docker"
    image: "Dockerfile"
    #entrypoint: 
    args: 
      -  ${{ inputs.who-to-greet }}